// Developer Express Code Central Example:
// How to change the GridColumn cell background for the focused column
// 
// This sample illustrates how to change the focused column appearance. Create the
// attached property for the GridColumn that determines whether the row is focused
// or not. Iterate via columns in the FocusedColumnChanged event, to keep this
// attached property up-to-date for every column. In the CellStyle event, change
// the Background property only for columns for which the custom attached property
// is True.
// Starting with version 2013 vol 1 the GridControl.FocusedColumnChanged
// event is marked as obsolete. The GridControl.CurrentColumnChanged event should
// be used instead.
// 
// You can find sample updates and versions for different programming languages here:
// http://www.devexpress.com/example=E2455

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
